In [1]:
##### IMPORTS #######
import pandas as pd
import matplotlib.pyplot as plt; plt.style.use('ggplot')
import numpy as np
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, roc_curve, RocCurveDisplay, cohen_kappa_score
from sklearn.decomposition import PCA
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import VotingClassifier
# Modeling imports
from sklearn.ensemble import RandomForestClassifier
from xgboost  import XGBClassifier
from lightgbm import LGBMClassifier, early_stopping, log_evaluation
from sklearn.model_selection import StratifiedKFold
import optuna
from optuna.samplers import TPESampler
import numpy as np

In [2]:
######READ FILES#######
path = "/Users/tcaron/Documents/Python Scripts/KaggleS3E7/data/"
train = pd.read_csv(path+"train.csv")
test = pd.read_csv(path+"test.csv")
origin = pd.read_csv(path+"origin.csv")

In [3]:
train

,id,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,required_car_parking_space,room_type_reserved,lead_time,arrival_year,arrival_month,arrival_date,market_segment_type,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests,booking_status
0,0,2,0,0,2,1,0,0,9,2018,1,14,1,1,11,0,67.50,0,0
1,1,2,0,1,2,0,0,0,117,2018,7,29,0,0,0,0,72.25,0,0
2,2,2,0,0,1,0,0,0,315,2018,12,2,0,0,0,0,52.00,0,0
3,3,1,0,0,2,1,0,0,32,2018,12,1,1,0,0,0,56.00,0,0
4,4,2,0,1,0,0,0,0,258,2018,10,16,0,0,0,0,100.00,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42095,42095,3,0,0,4,0,0,1,160,2018,12,30,1,0,0,0,140.00,2,1
42096,42096,2,0,0,3,0,0,0,34,2017,9,23,0,0,0,0,224.67,0,0
42097,42097,2,0,0,2,2,0,0,292,2018,7,21,0,0,0,0,96.00,0,0
42098,42098,1,0,0,3,0,0,0,5,2018,11,9,0,0,0,0,120.00,0,0
42099,42099,2,0,1,1,0,0,1,40,2017,10,26,0,0,0,0,65.00,0,0

In [4]:
test

,id,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,required_car_parking_space,room_type_reserved,lead_time,arrival_year,arrival_month,arrival_date,market_segment_type,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests
0,42100,3,0,1,4,0,0,1,111,2018,12,5,1,0,0,0,115.60,2
1,42101,2,0,0,3,0,0,0,22,2017,10,21,0,0,0,0,85.00,0
2,42102,2,2,0,1,0,0,3,18,2018,8,10,1,0,0,0,240.00,1
3,42103,2,0,0,3,0,0,0,88,2018,5,30,0,0,0,0,80.75,0
4,42104,1,0,0,2,2,0,0,7,2018,9,21,1,0,0,0,144.00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28063,70163,2,0,1,2,0,0,0,315,2018,9,30,1,0,0,0,160.00,0
28064,70164,2,0,2,2,0,0,0,81,2018,3,25,0,0,0,0,65.00,1
28065,70165,2,0,1,2,0,0,0,40,2018,10,22,0,0,0,0,85.00,0
28066,70166,3,0,0,4,0,0,1,4,2018,9,6,1,0,0,0,162.75,0
28067,70167,2,0,2,3,0,0,0,191,2018,8,28,1,0,0,0,84.31,0

In [5]:
train.drop(columns='id',inplace = True)
train = pd.concat([train,origin],ignore_index=True)
Id = test[["id"]]

In [6]:
def SelfSplitTrain(df,test_size=0.2):
    X = df.drop(columns=["booking_status"])
    y = df[["booking_status"]].values
    X_train, X_val, y_train, y_val = train_test_split(X,y,test_size=test_size,random_state=42)
    return (X_train, X_val, y_train, y_val)

In [7]:
from pandas.tseries.holiday import USFederalHolidayCalendar

def fe(df):
        # Fix date anomalies (pd.to_datetime throws parsing error for some days, see anomalies section).
        df['arrival_year_month'] = pd.to_datetime(df['arrival_year'].astype(str) + df['arrival_month'].astype(str), format='%Y%m')
#         df.loc[df.arrival_date > df.arrival_year_month.dt.days_in_month, 'arrival_date'] = df.arrival_year_month.dt.days_in_month
        df.loc[df.arrival_date > df.arrival_year_month.dt.days_in_month, 'arrival_date'] = df.loc[df.arrival_date > df.arrival_year_month.dt.days_in_month, 'arrival_year_month'].dt.days_in_month
        df.drop(columns='arrival_year_month', inplace=True)
        
        # Creates date features.
        df['arrival_full_date'] = (df['arrival_year'].astype(str) 
                                   + '-' + df['arrival_month'].astype(str)
                                   + '-' + df['arrival_date'].astype(str))
        df['arrival_full_date'] = pd.to_datetime(df.arrival_full_date)
        df['arrival_week'] = df['arrival_full_date'].dt.isocalendar().week.astype(float)
        df['arrival_dayofweek'] = df['arrival_full_date'].dt.dayofweek
        df['arrival_quarter'] = df['arrival_full_date'].dt.quarter
        df['arrival_dayofyear'] = df['arrival_full_date'].dt.dayofyear
        
        # Creates the season and holiday features. (also you can add holidays).
        # ['winter', 'spring', 'summer', 'fall']
        df['season'] = df.arrival_month%12 // 3 + 1
        cal = USFederalHolidayCalendar()
        holidays = cal.holidays(start='2017-01-01', end='2018-12-31')
        df['is_holiday'] = 0
        df.loc[df.arrival_full_date.isin(holidays), 'is_holiday'] = 1
        
        """
        # Aggregation by `season` as key and 'avg_price_per_room' as value (you can try quarters, months, etc).
        key = 'season'
        aggr_df = df.groupby(by=key, sort=False)['avg_price_per_room'].agg(['mean', 'std', 'min', 'max', 'sum', 'last'])
        aggr_df = aggr_df.add_prefix('avg_price_per_room_')
        df = df.merge(aggr_df.reset_index(), on=key, how='left')
        """
        
        # Interaction between the correlated features and also lead time.
        df['no_of_adults_div_price'] = df.no_of_adults / (df.avg_price_per_room + 1e-6)
        df['no_of_children_div_price'] = df.no_of_children / (df.avg_price_per_room + 1e-6)
        df['lead_time_div_price'] = df.lead_time / (df.avg_price_per_room + 1e-6)
        df.drop(columns=['arrival_full_date'], inplace=True)
        return df

df_tot = pd.concat([train, test], axis=0)
df_tot = df.drop('id', axis=1)
df_tot

In [8]:
df_train = fe(train)
df_train

,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,required_car_parking_space,room_type_reserved,lead_time,arrival_year,arrival_month,...,booking_status,arrival_week,arrival_dayofweek,arrival_quarter,arrival_dayofyear,season,is_holiday,no_of_adults_div_price,no_of_children_div_price,lead_time_div_price
0,2,0,0,2,1,0,0,9,2018,1,...,0,2.0,6,1,14,1,0,0.029630,0.0,0.133333
1,2,0,1,2,0,0,0,117,2018,7,...,0,30.0,6,3,210,3,0,0.027682,0.0,1.619377
2,2,0,0,1,0,0,0,315,2018,12,...,0,48.0,6,4,336,1,0,0.038462,0.0,6.057692
3,1,0,0,2,1,0,0,32,2018,12,...,0,48.0,5,4,335,1,0,0.017857,0.0,0.571429
4,2,0,1,0,0,0,0,258,2018,10,...,1,42.0,1,4,289,4,0,0.020000,0.0,2.580000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60232,1,0,0,2,0,0,0,103,2018,4,...,1,16.0,3,2,109,2,0,0.008696,0.0,0.895652
60233,2,0,0,3,0,0,0,129,2018,8,...,0,32.0,4,3,222,3,0,0.022725,0.0,1.465743
60234,2,0,0,1,0,0,0,90,2018,7,...,1,28.0,4,3,194,3,0,0.018993,0.0,0.854701
60235,2,0,0,3,0,0,0,18,2018,11,...,0,45.0,5,4,314,4,0,0.016217,0.0,0.145950
60236,1,0,1,1,0,0,0,159,2018,4,...,0,15.0,0,2,99,2,0,0.015385,0.0,2.446154

In [9]:
df_test = fe(test)
df_test

,id,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,required_car_parking_space,room_type_reserved,lead_time,arrival_year,...,no_of_special_requests,arrival_week,arrival_dayofweek,arrival_quarter,arrival_dayofyear,season,is_holiday,no_of_adults_div_price,no_of_children_div_price,lead_time_div_price
0,42100,3,0,1,4,0,0,1,111,2018,...,2,49.0,2,4,339,1,0,0.025952,0.000000,0.960208
1,42101,2,0,0,3,0,0,0,22,2017,...,0,42.0,5,4,294,4,0,0.023529,0.000000,0.258824
2,42102,2,2,0,1,0,0,3,18,2018,...,1,32.0,4,3,222,3,0,0.008333,0.008333,0.075000
3,42103,2,0,0,3,0,0,0,88,2018,...,0,22.0,2,2,150,2,0,0.024768,0.000000,1.089783
4,42104,1,0,0,2,2,0,0,7,2018,...,0,38.0,4,3,264,4,0,0.006944,0.000000,0.048611
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28063,70163,2,0,1,2,0,0,0,315,2018,...,0,39.0,6,3,273,4,0,0.012500,0.000000,1.968750
28064,70164,2,0,2,2,0,0,0,81,2018,...,1,12.0,6,1,84,2,0,0.030769,0.000000,1.246154
28065,70165,2,0,1,2,0,0,0,40,2018,...,0,43.0,0,4,295,4,0,0.023529,0.000000,0.470588
28066,70166,3,0,0,4,0,0,1,4,2018,...,0,36.0,3,3,249,4,0,0.018433,0.000000,0.024578
28067,70167,2,0,2,3,0,0,0,191,2018,...,0,35.0,1,3,240,3,0,0.023722,0.000000,2.265449

In [10]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

y_train = df_train['booking_status']
df_train = df_train.drop(['booking_status'], axis=1)

df_train[df_train.columns] = scaler.fit_transform(df_train[df_train.columns])
df_test.drop(columns='id',inplace=True)
df_test[df_test.columns] = scaler.transform(df_test[df_test.columns])

In [11]:
df_train['booking_status'] = y_train
X_train,X_val,y_train,y_val = SelfSplitTrain(df_train)

from warnings import simplefilter
simplefilter("ignore", category=RuntimeWarning)
def objective(trial):
    target_clases = train["booking_status"].value_counts()
    n_classes = target_clases.nunique()
    params_optuna = {
            'max_depth': trial.suggest_int('max_depth', 1, 10),
            'learning_rate': trial.suggest_float('learning_rate', 0.01, 1.0),
            'n_estimators': trial.suggest_int('n_estimators', 50, 1000),
            'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
            'gamma': trial.suggest_float('gamma', 0.01, 1.0),
            'subsample': trial.suggest_float('subsample', 0.5, 1.0),
            'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
            'reg_alpha': trial.suggest_float('reg_alpha', 0.0001, 1.0),
            'reg_lambda': trial.suggest_float('reg_lambda', 0.0001, 1.0),
            'objective' : "binary:logistic",
            'metric':'auc',
        }
    
    n=trial.suggest_int('n_cv', 3, 10)
    cv = StratifiedKFold(n,shuffle=True, random_state=42)
    fold_scores = []
    model = XGBClassifier(**params_optuna)
    model.fit(X_train,
              y_train,
              eval_set= [(X_val,y_val)],
              early_stopping_rounds = 50,
              verbose=500)

    pred_val = model.predict_proba(X_val)
    print(pred_val.shape)
    score = roc_auc_score(y_val, pred_val[:,1])
    fold_scores.append(score)
    return np.mean(fold_scores)


study = optuna.create_study(direction='maximize', sampler = TPESampler())
study.optimize(func=objective, n_trials=500)
print(study.best_params)

In [12]:
params_xgb = {'max_depth': 3, 'learning_rate': 0.2339015532210192, 'n_estimators': 674, 'min_child_weight': 6, 'gamma': 0.7822894936779129, 'subsample': 0.9864390259507783, 'colsample_bytree': 0.7817053564031262, 'reg_alpha': 0.22647766716715423, 'reg_lambda': 0.835049500219911, 'n_cv': 7}

def objective2(trial):
    target_clases = train["booking_status"].value_counts()
    n_classes = target_clases.nunique()
    params_optuna = {
            'lambda_l1': trial.suggest_float('lambda_l1', 0, 1),
             'lambda_l2': trial.suggest_float('lambda_l2', 1, 10),
             'num_leaves': trial.suggest_int('num_leaves', 40, 60),
             'feature_fraction': trial.suggest_float('feature_fraction', 0, 1),
             'bagging_fraction': trial.suggest_float('bagging_fraction', 0, 1),
             'bagging_freq': trial.suggest_int('bagging_freq', 1, 10),
             'min_child_samples': trial.suggest_int('min_child_samples', 1, 100),
             'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 1, 100),
             'max_depth': trial.suggest_int('max_depth', 1, 20),
             'num_iterations':trial.suggest_int('num_iterations', 100, 10000),
             'objective' : "binary",
             'metric' :'auc',
        }
    
    n=trial.suggest_int('n_cv', 3, 10)
    cv = StratifiedKFold(n,shuffle=True, random_state=42)
    fold_scores = []
    model = LGBMClassifier(**params_optuna)
    model.fit(X_train,
              y_train,
              eval_set= [(X_val,y_val)],
              early_stopping_rounds = 50,
              verbose=500)

    pred_val = model.predict_proba(X_val)

    score = roc_auc_score(y_val, pred_val[:,1])
    fold_scores.append(score)
    return np.mean(fold_scores)


study = optuna.create_study(direction='maximize', sampler = TPESampler())
study.optimize(func=objective2, n_trials=500)
print(study.best_params)

In [13]:
params_lgbm = {'lambda_l1': 0.8763429557476354, 'lambda_l2': 7.165908219263854, 'num_leaves': 55, 'feature_fraction': 0.20414837411761166, 'bagging_fraction': 0.9688308696734866, 'bagging_freq': 2, 'min_child_samples': 85, 'min_data_in_leaf': 17, 'max_depth': 5, 'num_iterations': 6870, 'n_cv': 5}

##### from sklearn.pipeline import Pipeline
from sklearn import preprocessing
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 100, stop = 1000, num = 10)]

# Number of features to consider at every split
max_features = ['auto']

# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(5, 30, num = 5)]
max_depth.append(None)

# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]

# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4, 8]

# Method of selecting samples for training each tree
bootstrap = [True]

# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}

rf = RandomForestClassifier()

random = GridSearchCV(estimator = rf, param_grid= random_grid, cv = 3, verbose=200, n_jobs = -1,scoring='roc_auc')
random.fit(X_train,y_train)
# print best parameter after tuning
print(grid.best_params_)
# print how our model looks after hyper-parameter tuning
print(grid.best_estimator_)
grid_predictions = grid.predict(X_val)
print(classification_report(y_val, grid_predictions))

In [14]:
params_rf = {'bootstrap': True,
 'max_depth': 17,
 'max_features': 'auto',
 'min_samples_leaf': 4,
 'min_samples_split': 5,
 'n_estimators': 600}

In [32]:
features = list(X_train.columns)
TARGET = "booking_status"
k=50
cv = StratifiedKFold(k, shuffle=True, random_state=42)
fold_scores = []
test_preds = []

estimators = []
model1 = XGBClassifier(**params_xgb)
"""
model1.fit(X_train,
           y_train,
           eval_set= [(X_val,y_val)],
           early_stopping_rounds = 200,
           verbose=200)
"""
estimators.append(('xgb', model1))

model2 = LGBMClassifier(**params_lgbm)
"""
model2.fit(X_train,
             y_train,
             eval_set= [(X_val,y_val)],
             early_stopping_rounds = 200,
             verbose=200)
estimators.append(('lgbm', model2))
"""
model3=RandomForestClassifier(**params_rf)
#model3.fit(X_train,y_train)
estimators.append(('rf', model3))
# create the ensemble model
ensemble = VotingClassifier(estimators)
ensemble.fit(df_train[features], df_train[TARGET])
y_pred = ensemble.predict_proba(df_test)
print(y_pred)

[14:21:56] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:576:
Parameters: { "n_cv" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.


[14:21:56] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[0]	validation_0-logloss:0.61885

C:\Users\tcaron\Anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

[200]	validation_0-logloss:0.35696
[400]	validation_0-logloss:0.35060

KeyboardInterrupt:

In [16]:
class OptunaRounder:

    def __init__(self, y_true, y_pred):
        self.y_true = y_true
        self.y_pred = y_pred
        self.labels = np.unique(y_true)

    def __call__(self, trial):
        thresholds = []
        for i in range(len(self.labels) - 1):
            low = max(thresholds) if i > 0 else min(self.labels)
            high = max(self.labels)
            t = trial.suggest_float(f't{i}', low, high)
            thresholds.append(t)
        try:
            opt_y_pred = self.adjust(self.y_pred, thresholds)
        except: return 0
        return cohen_kappa_score(self.y_true, opt_y_pred, weights='quadratic')

    def adjust(self, y_pred, thresholds):
        opt_y_pred = pd.cut(y_pred,
                            [-np.inf] + thresholds + [np.inf],
                            labels=self.labels)
        return opt_y_pred

In [17]:
optuna.logging.set_verbosity(optuna.logging.WARNING) 
objective = OptunaRounder(oof_true, oof_preds)
study = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=42))
study.optimize(objective, timeout=100)

In [18]:
best_thresholds = sorted(study.best_params.values())
print(f'Optimized thresholds: {best_thresholds}')
test_preds_mean = np.array(test_preds).mean(axis=0)

Optimized thresholds: [0.3745401188473625]

In [19]:
Id["booking_status"]=test_preds_mean[:,1]
print(Id.head(3))

      id  booking_status
0  42100        0.042537
1  42101        0.048066
2  42102        0.041632

C:\Users\tcaron\AppData\Local\Temp/ipykernel_30768/945698531.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Id["booking_status"]=test_preds_mean[:,1]

In [20]:
Id.to_csv("sample_submission.csv",index=False)

In [28]:
test_preds_mean

array([[0.95746281, 0.04253719],
       [0.95193433, 0.04806567],
       [0.95836831, 0.04163169],
       ...,
       [0.95110749, 0.04889251],
       [0.94280016, 0.05719984],
       [0.94123482, 0.05876518]])